src/Entity/Organisation.php
<?php

namespace App\Entity;

use App\Repository\OrganisationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


#[ORM\Entity(repositoryClass: OrganisationRepository::class)]
#[ORM\Index(name: 'organisation_fulltext_idx', columns: ['name', 'description'], flags: ['fulltext'])]
class Organisation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $coordinates = null;

    #[ORM\Column(length: 255)]
    private ?string $main_photo = null;

    #[ORM\Column(nullable: true)]
    private ?array $additional_photos = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?array $contacts = null;

    #[ORM\Column(nullable: true)]
    private bool|null $verified = null;

    private array $mainImageDimensions;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'organisations')]
    #[ORM\JoinColumn(nullable: true)]
    private Collection $owner;

    #[ORM\ManyToOne(inversedBy: 'organisations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?OrganisationCategory $category = null;

    /**
     * @var Collection<int, PublicEvent>
     */
    #[ORM\OneToMany(targetEntity: PublicEvent::class, mappedBy: 'organisation')]
    private Collection $publicEvents;

    #[ORM\Column(length: 255)]
    private ?string $short_description = null;

    /**
     * @var string|null
     *
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    #[ORM\Column(length: 128, unique: true, nullable: true)]
    #[Gedmo\Slug(fields: ['name'])]
    private $slug;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $seoDescription = null;

    #[ORM\Column(nullable: true)]
    private ?array $keywords = null;

    #[ORM\OneToOne(targetEntity: PublicEventStatistic::class, mappedBy: 'managingOrganisation', cascade: ['persist', 'remove'])]
    private ?PublicEventStatistic $statistic = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $timeOpen = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $timeClose = null;

    #[ORM\Column(nullable: true)]
    private ?array $alternateNames = null;


    public function __construct()
    {
        $this->owner = new ArrayCollection();
        $this->publicEvents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getMainPhoto(): ?string
    {
        return $this->main_photo;
    }

    public function setMainPhoto(string $main_photo): static
    {
        $this->main_photo = $main_photo;

        return $this;
    }

    public function getAdditionalPhotos(): ?array
    {
        return $this->additional_photos;
    }

    public function setAdditionalPhotos(?array $additional_photos): static
    {
        $this->additional_photos = $additional_photos;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCoordinates(): ?string
    {
        return $this->coordinates;
    }

    /**
     * @return string|null
     */
    public function swapCoordinates(): ?string
    {
        $coordinates = explode(',', $this->coordinates);
        return trim($coordinates[1]) . ',' . trim($coordinates[0]);
    }

    /**
     * @param string|null $coordinates
     */
    public function setCoordinates(?string $coordinates): void
    {
        $this->coordinates = $coordinates;
    }

    /**
     * @return Collection<int, User>
     */
    public function getOwner(): Collection
    {
        return $this->owner;
    }

    public function addOwner(User $owner): static
    {
        if (!$this->owner->contains($owner)) {
            $this->owner->add($owner);
        }

        return $this;
    }

    public function removeOwner(User $owner): static
    {
        $this->owner->removeElement($owner);

        return $this;
    }

    public function getCategory(): ?OrganisationCategory
    {
        return $this->category;
    }

    public function setCategory(?OrganisationCategory $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, PublicEvent>
     */
    public function getPublicEvents(): Collection
    {
        return $this->publicEvents;
    }

    public function addPublicEvent(PublicEvent $publicEvent): static
    {
        if (!$this->publicEvents->contains($publicEvent)) {
            $this->publicEvents->add($publicEvent);
            $publicEvent->setOrganisation($this);
        }

        return $this;
    }

    public function removePublicEvent(PublicEvent $publicEvent): static
    {
        if ($this->publicEvents->removeElement($publicEvent)) {
            // set the owning side to null (unless already changed)
            if ($publicEvent->getOrganisation() === $this) {
                $publicEvent->setOrganisation(null);
            }
        }

        return $this;
    }

    /**
     * @return bool|null
     */
    public function isVerified(): ?bool
    {
        return $this->verified;
    }

    /**
     * @param bool|null $verified
     */
    public function setVerified(?bool $verified): void
    {
        $this->verified = $verified;
    }

    public function __toString(): string
    {
        return '(' . $this->getId() . ') ' . $this->getName();
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): static
    {
        $this->short_description = $short_description;

        return $this;
    }

    /**
     * @return array|null
     */
    public function getContacts(): ?array
    {
        return $this->contacts;
    }

    /**
     * @param array|null $contacts
     */
    public function setContacts(?array $contacts): void
    {
        $this->contacts = $contacts;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string|null $slug
     */
    public function setSlug(?string $slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string|null $title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return string|null
     */
    public function getSeoDescription(): ?string
    {
        return $this->seoDescription;
    }

    /**
     * @param string|null $seoDescription
     */
    public function setSeoDescription(?string $seoDescription): void
    {
        $this->seoDescription = $seoDescription;
    }

    /**
     * @return array|null
     */
    public function getKeywords(): ?array
    {
        return $this->keywords;
    }

    /**
     * @param array|null $keywords
     */
    public function setKeywords(?array $keywords): void
    {
        $this->keywords = $keywords;
    }

    public function getTimeOpen(): ?\DateTimeInterface
    {
        return $this->timeOpen;
    }

    public function setTimeOpen(?\DateTimeInterface $timeOpen): static
    {
        $this->timeOpen = $timeOpen;

        return $this;
    }

    public function getTimeClose(): ?\DateTimeInterface
    {
        return $this->timeClose;
    }

    public function setTimeClose(?\DateTimeInterface $timeClose): static
    {
        $this->timeClose = $timeClose;

        return $this;
    }

    public function getAlternateNames(): ?array
    {
        return $this->alternateNames;
    }

    public function setAlternateNames(?array $alternateNames): static
    {
        $this->alternateNames = $alternateNames;

        return $this;
    }


}

src/Entity/Region.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;
use App\Repository\RegionRepository;


#[ORM\Entity(repositoryClass: RegionRepository::class)]
class Region
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['region'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['region'])]
    private ?string $name = null;

    /**
     * @var Collection<PublicEvent>|null
     */
    #[ORM\OneToMany(targetEntity: PublicEvent::class, mappedBy: 'region')]
    private ?Collection $publicEvents;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['region'])]
    private ?string $lng = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['region'])]
    private ?string $lat = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['region'])]
    private ?string $admin_name = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'region')]
    private Collection $users;

    #[ORM\ManyToOne(targetEntity: self::class)]
    private ?self $parent = null;

    #[ORM\Column(length: 255)]
    #[Groups(['region'])]
    private ?string $slug = null;

    /**
     * @var Collection<ExcursionRouteReport>
     */
    #[ORM\OneToMany(targetEntity: ExcursionRouteReport::class, mappedBy: 'region')]
    private Collection $routeReports;

    /**
     * @var Collection<ExcursionRoute>
     */
    #[ORM\OneToMany(targetEntity: ExcursionRoute::class, mappedBy: 'region')]
    private Collection $excursionRoutes;

    public function __construct()
    {
        $this->publicEvents = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->excursionRoutes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, PublicEvent>
     */
    public function getPublicEvents(): Collection
    {
        return $this->publicEvents;
    }

    public function addPublicEvent(PublicEvent $publicEvent): static
    {
        if (!$this->publicEvents->contains($publicEvent)) {
            $this->publicEvents->add($publicEvent);
            $publicEvent->setRegion($this);
        }

        return $this;
    }

    public function removePublicEvent(PublicEvent $publicEvent): static
    {
        if ($this->publicEvents->removeElement($publicEvent)) {
            // set the owning side to null (unless already changed)
            if ($publicEvent->getRegion() === $this) {
                $publicEvent->setRegion(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getLng(): ?string
    {
        return $this->lng;
    }

    public function setLng(?string $lng): static
    {
        $this->lng = $lng;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(?string $lat): static
    {
        $this->lat = $lat;

        return $this;
    }

    public function getAdminName(): ?string
    {
        return $this->admin_name;
    }

    public function setAdminName(?string $admin_name): static
    {
        $this->admin_name = $admin_name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setRegion($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getRegion() === $this) {
                $user->setRegion(null);
            }
        }

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): static
    {
        $this->parent = $parent;

        return $this;
    }

    public function addParent(self $parent): static
    {
        if (!$this->parent->contains($parent)) {
            $this->parent->add($parent);
            $parent->setParent($this);
        }

        return $this;
    }

    public function removeParent(self $parent): static
    {
        if ($this->parent->removeElement($parent)) {
            // set the owning side to null (unless already changed)
            if ($parent->getParent() === $this) {
                $parent->setParent(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, ExcursionRoute>
     */
    public function getExcursionRoutes(): Collection
    {
        return $this->excursionRoutes;
    }

    public function addExcursionRoute(ExcursionRoute $excursionRoute): static
    {
        if (!$this->excursionRoutes->contains($excursionRoute)) {
            $this->excursionRoutes->add($excursionRoute);
            $excursionRoute->setRegion($this);
        }

        return $this;
    }

    public function removeExcursionRoute(ExcursionRoute $excursionRoute): static
    {
        if ($this->excursionRoutes->removeElement($excursionRoute)) {
            // set the owning side to null (unless already changed)
            if ($excursionRoute->getRegion() === $this) {
                $excursionRoute->setRegion(null);
            }
        }

        return $this;
    }

    public function getRouteReports(): Collection
    {
        return $this->routeReports;
    }

    public function setRouteReports(Collection $routeReports): void
    {
        $this->routeReports = $routeReports;
    }


}

templates/pages/carousel_row.html.twig
<div class="container main-slider">
    <div class="swiper">
        <div class="swiper-wrapper draggable-element">
            {% for event_collection in eventCollectionsTop %}
                <div class="swiper-slide">
                    {% if event_collection.slug == 'contest' %}
                        <a href="{{ path('app_contest') }}"><span class="caption">{{ event_collection.name }}</span></a>
                    {% else %}
                        <a href="{{ path('app_event_collection_show_slug', {'slug' : event_collection.slug }) }}"><span
                                    class="caption">{{ event_collection.name }}</span></a>
                        <img src="/upload/images/{{ asset(event_collection.mainPhoto) }}" alt="{{ event_collection.name }}">
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/pages/map.html.twig
{% extends 'base.html.twig' %}
{% block title %}Где история: Карта организаций{% endblock %}
{% set location = locationCurrent() %}
{% set organisationCategories = organisationCategoriesList() %}
{% block stylesheets %}
    {{ parent() }}
    <style>
        .unselectable {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
    </style>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="https://yandex.st/jquery/2.2.3/jquery.js"></script>
    <script src="https://api-maps.yandex.ru/2.1/?apikey=b7221eed-1eca-44f8-b906-1b7ee8b7dd55&lang=ru_RU"
            type="text/javascript"></script>

    <!--COMPANIES Card template-->
    {% verbatim %}
    <script id="companyCardTemplate" type="text/x-jquery-tmpl">
    <div>
        <li class="event-card">
            <div class="event-card-head">
            <a href="${link}"><img src="${img}"/></a>
                <div class="event-card-image-tag-list">
                    {{each(i,v) tags}}
                        <a href="#" class="event-card-tag-link ${v.status}">${v.name}</a>
                    {{/each}}
                </div>
            </div>
            <a href="${link}"><h3 class="event-card-title">${title}</h3></a>
            <a href="${link}"><p class="event-card-caption">${description}</p></a>
            </a>
            <div class="event-card-org">
                <div class="event-card-org-logo"><img src="${org.img}"/></div>
                <div class="event-card-org-link"><a href="${org.link}">${org.title}</a></div>
            </div>
            {{if $data.location}}
                <div class="event-card-location">
                    <a href="${location.link}">${location.title}</a>
                </div>
            {{/if}}    
        </li>        
    </div>
    </script>
    {% endverbatim %}

    <script type="text/javascript">
        let categoriesList = [];
        let myMap;

        {% for organisationCategory in organisationCategories %}
        categoriesList.push('{{ organisationCategory[0].short }}');
        {% endfor %}

        ymaps.ready(init);

        function init() {
            // Создание карты и заполнение (пока) всеми объектами
            myMap = new ymaps.Map("map", {
                center: [{{ location.coordinates }}],
                zoom: 8,
                controls: ['geolocationControl', 'zoomControl', 'fullscreenControl']
            });

            // Создаем кластеризатор c красной иконкой (по умолчанию используются синяя).
            let clusterer = new ymaps.Clusterer({clusterDisableClickZoom: true}),
                // Создаем коллекцию геообъектов.
                collection = new ymaps.GeoObjectCollection();

            // Добавляем кластеризатор на карту.
            myMap.geoObjects.add(clusterer);
            myMap.container.fitToViewport();

            //собираем метки в массив из базы
            let myGeoObjects = [];
            // @formatter:off
            {% for organisation in organisations %}
                {% if organisation.coordinates is not empty %}
                    {% set coordinates = organisation.coordinates|split(',') %}
                    myGeoObjects.push(new ymaps.GeoObject({
                        geometry: {
                            type: "Point",
                            coordinates: [{{ coordinates[0]|trim }}, {{ coordinates[1]|trim }}]
                        },
                        properties: {
                            preset: 'islands#icon',
                            iconColor: '#d40f33',
                            type: "{{ organisation.category.short }}",
                            balloonContentHeader: "{{ organisation.name }}",
                            balloonContentBody: "{{ organisation.shortDescription }}",
                            balloonContentFooter: "<a href=\"{{ path('app_organisation_show_slug', {'slug': organisation.slug }) }}\">профиль организации</a>",
                            hintContent: "{{ organisation.name }}"
                        }
                    }));
                    {% endif %}
            {% endfor %}
            // @formatter:on

            clusterer.add(myGeoObjects);
            myMap.geoObjects.add(clusterer);


            //фильтр по типу объекта
            function setState(value) {
                let filter = [];
                filter.push(value);

                filtredObjects = myGeoObjects.filter(el => (filter.includes(el.properties._data.type)));
                clusterer.add(filtredObjects);

                let doNotShow = myGeoObjects.filter(n => !filtredObjects.includes(n));

                // Объекты, которые не попали в выборку, нужно убрать с карты.
                clusterer.remove(doNotShow);
            }


            //смена центра карты по локации
            const dropdowns = ['locationDropdown', 'locationHeaderDropdown', 'locationFooterDropdown'];
            dropdowns.forEach(function (dropdown) {
                const dropdownItems = document.getElementById(dropdown).nextElementSibling.querySelectorAll('.dropdown-item');
                dropdownItems.forEach(function (item) {
                    item.addEventListener('click', function (event) {
                        event.preventDefault();
                        let selectedLocation = this.getAttribute('data-location-id');
                        let location = cities.find(item => item.id == selectedLocation);
                        myMap.setCenter([{{ location.coordinates }}]);
                    });
                });
            });


            const dropdownMenus = document.querySelectorAll('.filter-content .dropdown-menu');
            const selectedValues = {};
            let timer;

            function updateSelections(groupId, value, text) {
                // Store the selected value along with the group ID
                selectedValues[groupId] = {
                    value: value,
                    text: text
                };

                // Update the corresponding dropdown toggle text
                document.getElementById(`filterDropdown${groupId}`).textContent = text;

                // Clear the previous timer
                clearTimeout(timer);

                // Set a new timer to delay the request
                timer = setTimeout(() => {
                    // Prepare the payload with group IDs and selected values
                    const payload = Object.keys(selectedValues).map(groupId => ({
                        groupId: groupId,
                        value: selectedValues[groupId].value
                    }));

                    // Trigger the action based on the selected values after the delay
                    console.log('Selected values:', payload);

                    setState(payload[0].value);

                }, 300); // Adjust the delay as needed (1000ms = 1s)
            }

            dropdownMenus.forEach(function (menu) {
                const dropdownItems = menu.querySelectorAll('.dropdown-item');

                dropdownItems.forEach(function (item) {
                    item.addEventListener('click', function (event) {
                        event.preventDefault();

                        // Get the selected value and text
                        const selectedValue = this.getAttribute('data-value');
                        const selectedText = this.textContent;
                        const groupId = menu.getAttribute('aria-labelledby').replace('filterDropdown', '');

                        // Update selections and trigger the delayed request
                        updateSelections(groupId, selectedValue, selectedText);
                    });
                });
            });
        }


    </script>
    {{ parent() }}
{% endblock %}

{% block content %}
    <!-- Content -->
    <div class="container main-section map-page">
        {% set first_crumb = 'Карта' %}
        {% set do_not_show_search = true %}
        {% include ('pages/base/breadcrumbs.html.twig') %}
        <div class="row event-search-header">
            <div class="col-md-8">
                <h2>Организации <a href="#" class="text-red" id="city"><i class="nav-icon"></i></a>
                    <a class="dropdown-toggle text-red" href="/#" id="locationHeaderDropdown"
                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="location-name">
                            {{ location.location_admin_name }}
                            </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="locationHeaderDropdown">
                        {% for location in locationList() %}
                            <a class="dropdown-item" href="#"
                               data-location-id="{{ location.region.name }}">{{ location.region.adminName }}</a>
                        {% endfor %}
                    </div>
                </h2>
            </div>

            <div class="col-md-4 pt-2 d-none d-sm-block">
                {{ include('pages/base/search.html.twig') }}
            </div>
        </div>

        {% include('pages/map_filter_row.html.twig') %}

        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4 mt-4">
                    <div id="map"></div>
                </div>
            </div>
        </div>

        <div class="row event-search-header">
            <div class="col-md-12">
                <h2>Новые организации в нашем каталоге:</h2>
            </div>
        </div>

        {% include('pages/organizations_row.html.twig') %}
        {% include('pages/base/bottom_carousel_row.html.twig') %}
    </div>
    <!-- / Content -->

{% endblock %}

templates/pages/map_row.html.twig
<!--map-->
<div class="row">
    <div class="col-md-12 text-center map-container">
{#        <img src="{{ asset('img/map_index.png') }}"/>#}
        {% set coordinates = locationCurrent().coordinates|split(',') %}
        <img src="https://static-maps.yandex.ru/1.x/?ll={{ coordinates[1]|trim }},{{ coordinates[0]|trim }}&l=map&z=11&size=650,60&type=satellite"/>
        <a href="/map/" class="map-show-around">Организации рядом со мной</a>
    </div>
</div>
<!--end map-->

templates/pages/past_events_row.html.twig
{% if pastEvents|length > 0 %}
    <div class="row">
        <div class="col-md-12 mt-4">
            <h3>Прошедшие события</h3>
            <div class="event-card-container">
                <ul class="event-card-content">
                    {% for event in pastEvents %}
                        <li class="event-card">
                            <div class="event-card-head">
                                <a href="{{ path('app_public_event_show_slug', {'category': event.category.short, 'slug': event.slug }) }}"><img
                                            style="filter: grayscale(1);"
                                            alt="{{ event.name }}"
                                            src="{{ asset('upload/images/') }}{{ event.mainPhoto }}"/></a>
                                <div class="event-card-image-tag-list">
                                    <a href="#" class="event-card-tag-link active">Завершилось</a>
                                    <a href="{{ path('app_event_list', {'category' :  event.category.short}) }}"
                                       class="event-card-tag-link">{{ event.category.name }}</a>
                                    {% set letter_count = event.category.name|length %}
                                    {% for filter in event.filter %}
                                        {% set letter_count = letter_count + filter.name|length %}
                                        {% if letter_count <= 23 %}
                                            <a href="/filter/{{ filter.short == 'toll' ? filter.short ~ '/' ~ filter.id : filter.short }}"
                                               class="event-card-tag-link">{{ filter.name }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{{ path('app_public_event_show_slug', {'category': event.category.short, 'slug': event.slug }) }}"><h3
                                        class="event-card-title">{{ event.name }}</h3></a>
                            <a href="{{ path('app_public_event_show_slug', {'category': event.category.short, 'slug': event.slug }) }}"><p
                                        class="event-card-caption">{{ event.shortDescription }}</p>
                            </a>
                            <div class="event-card-org">
                                {% if event.organisation is not empty %}
                                    <div class="event-card-org-logo">
                                        <img alt="{{ event.organisation.name }}"
                                             src="{{ asset('upload/images/') }}{{ event.organisation.mainPhoto }}"/>
                                    </div>
                                    <div class="event-card-org-link">
                                        <a href="{{ path('app_organisation_show_slug', {'slug' : event.organisation.slug}) }}">{{ event.organisation.name }}</a>
                                    </div>
                                {% endif %}

                            </div>
                            <div class="event-card-dates">
                                {% if event.duration is not empty and event.duration != 0 %}
                                    {% if event.duration == 1 %}
                                        {{ event.startDate ? event.getDayAndMonthName(event.startDate) : '' }} &middot; {{ event.duration }} {{ event.getDurationEnding(event.duration) }}
                                    {% else %}
                                        {{ event.startDate ? event.getDayAndMonthName(event.startDate) : '' }} &mdash; {{ event.getEndDate }} &middot; {{ event.duration }} {{ event.getDurationEnding(event.duration) }}
                                    {% endif %}
                                {% else %}
                                    {{ event.startDate ? event.getDayAndMonthName(event.startDate) : '' }} &middot; {{ event.getDurationEnding(event.duration) }}
                                {% endif %}
                            </div>
                            {% if event.address is not empty %}
                                <div class="event-card-location">
                                    <a href="https://yandex.ru/maps/?mode=search&text={{ event.address }}">{{ event.address }}</a>
                                </div>
                            {% endif %}
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
{% endif %}